# 1. why 파이썬? 가장 인기 있는 이유?

## a. 넘파이는? 🥧
---
- **선형대수 데이터 계산 패키지 = 현대 AI구현 시작과 끝**
- C언어로 구현된 파이썬 라이브러리 = 고속! 고성능! 수치계산
- n차원 배열객체 = 브로드캐스팅(broadcasting) = 배열요소 계산을 한번에 = matlab 강력한 특징
- 강력한 배열계산 = 벡터연산(vectorized operation) = 행렬계산
- 배열 왜 필요? --> 행렬 계산 --> 다차원 연립 방정식 --> 포워드/백프로파게이션 = DL<br><br>
- <span style="background:yellow; color:red">**넘파이와 판다스 차이? = 넘파이는 빠른 연산을 위한 배열 but 판다스는 넘파이 기반으로 만들어진 RDMS(관계형데이터베이스) 형태 데이터셋**</span> 

## b. 일단 해보자. 선언! 📢
---

In [1]:
import numpy as np

- 넘파이 어레이 = 넘파이 시리즈 = 1차원 배열 = 벡터 만들어보자

In [294]:
a1 = np.array([1, 2, 3])
a1 # 넘파이 어레이

array([1, 2, 3])

- 파이썬 리스트를 만들어보자
- 혹시나... 리스트가 뭔가요?
- 참고하세요: https://dojang.io/mod/page/view.php?id=2200

In [295]:
l1 = [1, 2, 3]
l1 # 파이썬 리스트

[1, 2, 3]

- 2차원 배열 = 매트릭스 만들어보자

In [296]:
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [297]:
l2 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
l2

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

[[1, 2, 3, 4],  
[5, 6, 7, 8],  
[9, 10, 11, 12],  
[13, 14, 15, 16]]

## c. 1차원 인덱싱 📇
---
- 혹시나... 인덱싱이 뭔가요?
- 참고하세요. https://dojang.io/mod/page/view.php?id=2207<br><br>
- 혹시나... 슬라이싱이 뭔가요?
- 참고하세요. https://dojang.io/mod/page/view.php?id=2208

In [298]:
a1 = np.array([1, 2, 3, 4, 5]) # 5개 원소를 같는 넘파이 벡터(1차원 배열) 만들어보자
a1

array([1, 2, 3, 4, 5])

In [299]:
l1 = [1, 2, 3, 4, 5] # 5개 원소를 같는 파이썬 벡터(1차원 배열) 만들어보자
l1

[1, 2, 3, 4, 5]

In [300]:
a1[0], a1[1], a1[2], a1[-2], a1[-1] # 0번째, 1번째, 2번째, -2번재, -1번째

(np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5))

In [301]:
l1[0], l1[1], l1[2], l1[-2], l1[-1] # 0번째, 1번째, 2번째, -2번재, -1번째

(1, 2, 3, 4, 5)

- 당연, 슬라이싱 가능

In [302]:
a1[0:2], a1[3:], a1[:-2] # 1번째에서 2번째까지, 4번째에서 끝까지, 처음부터 뒤에서 2번째까지

(array([1, 2]), array([4, 5]), array([1, 2, 3]))

In [303]:
l1[0:2], l1[3:], l1[:-2] # 0번째에서 1번째까지, 3번째에서 끝까지, 처음부터 뒤에서 2번째까지

([1, 2], [4, 5], [1, 2, 3])

- 리스트 형태로 접근 가능 --> 여기서 부터 슬슬 차이가 나기 시작함 = 리스트 기능 < 넘파이 기능

In [304]:
a1[[1, 2, 4]] # 1, 2, 4번재 인수 꺼내기

array([2, 3, 5])

In [305]:
l1[[1, 2, 4]] # 1, 2, 4번재 인수 꺼내기

TypeError: list indices must be integers or slices, not list

- 불리언 인덱싱

In [ ]:
a1[[True, False, True, True, False]]

In [ ]:
l1[[True, False, True, True, False]]

- 그렇다면?

In [ ]:
a1 < 3 # 불리언 넘ㅍ아이 어레이로 반환

In [ ]:
a1[a1 < 3]

In [ ]:
l1[l1 < 3] # 당연히 안됨

## d. 2차원 인덱싱 2️⃣
---

In [ ]:
a2

In [ ]:
l2

In [ ]:
a2 = np.array(l2) # 이렇게도 정의 가능하겠죠? 리스트 --> 넘파이 어레이로...
a2

[[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16]]

In [ ]:
a2[0][1], a2[2][3] # (1,2) 원소, (3,4) 원소

In [ ]:
l2[0][1], l2[2][3] # 물론 리스트도 가능합니다.

In [ ]:
a2[2][-1] # 3번째행 마지막 원소 = 이런 것들도 가능하겠죠?

In [ ]:
l2[2][-1] # 물론 리스트도...

- 리스트에서 되는 인덱싱 = 넘파이 어레이에서 가능 but 행렬처럼 인덱싱이 되는 것은 only in 넘파이 

In [ ]:
a2[0, 1], a2[2, 3], a2[2, -1] # 즉, 이런 것 들도 가능합니다.

- 심지어 슬라이싱도!

In [ ]:
a2

In [ ]:
a2[0, 0:3]

In [ ]:
a2[0, :] # 1행만 뽑으면?

In [ ]:
a2[0] # 같은 1행 but 편의상 쓰는 것이지... 정확하지 않음

[[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16]] = 이해되기는 함

In [ ]:
a2[[0, 2], 2:] # (1행과 3행)의 3열부터 끝까지

In [ ]:
a2[2:, [0, 2]] # (3행부터 끝까지)의 1열, 3열

- 스트라이딩도 가능 --> 0:4:2 = 1행부터 4행까지 2씩 증가 = 1행 3행

In [ ]:
a2[0:4:2, :]

In [ ]:
a2[0:4:2] # 마찬가지로...정확하지 않

#######

# 2. Broadcasting and Vectorization

## a. 브로드캐스팅 🥦
---
- 배열의 모든 인자에 1을 더하기

In [ ]:
a1 + 1

In [ ]:
l1 + 1

In [ ]:
[f + 1 for f in l1] # 리스트는 인자수 만큼 루프를 만들어야...

In [ ]:
a1 * 2

In [ ]:
l1 * 2 # 이건 리스트가 특이한 기능

In [ ]:
a1 / 2

In [ ]:
l1 / 2

In [ ]:
a1 ** 2

In [ ]:
l1 ** 2

## b. 잠깐! 다른 이야기로 넘어와서 넘파이 배열생성 해보자. 🛳️
---
- 리스트를 이용하여 넘파이 배열 생성

In [ ]:
np.array([1, 2, 3]) # 넘파이 어레이 만들기 = 앞에서 했었...

In [ ]:
np.array(l1), np.array(l2) # 당연히 = 이것도 앞에서 했었...

- array + range = arange

In [ ]:
np.array(range(5))  # 5원소 만들기... 0 ~ 4

In [ ]:
np.arange(5) # 같은 것

In [ ]:
np.arange(1, 6) # 범위 지정도 가능 = 1 ~ 5

In [ ]:
np.arange(1, 6, 2)  # 스트라이딩도 가능 + 범위 지정도 가능 = 1 ~ 5

In [ ]:
np.array(range(0, 10, 2)) # 다른 의미로...

In [ ]:
np.arange(0, 10, 2) # 같은 것

In [ ]:
np.linspace(0, 10, 5) # [0, 10] 5개의 등간격 인자 만들기

In [ ]:
np.ones(10), np.ones([3, 3])

In [ ]:
np.zeros(7), np.zeros([7, 7])

## c. 랜덤 배열생성 🔀
---
- random 클래스 및 다양한 메쏘드 존재

In [ ]:
np.random.random(10) # [0, 1) 균등분포(Uniform Distribution)에서 표본 추출

In [ ]:
np.random.random([4,4]) # 16개 표본 4바이4 메트릭스로

In [ ]:
np.random.rand(10) # 같은 것...

In [ ]:
np.random.rand(3,3) # 단, 2차원 이상은 리스트X, 직접 2개의 변수를 받는다.

In [ ]:
np.random.randint(1, 10, [4, 4]) # 특이한 형식

In [ ]:
np.random.randn(10) # 표준정규분포에서 10개 표본추출, 평균=0, 표준편차=1

In [ ]:
np.random.randn(3, 3) # 리스트X, rand와 같다!

## d. 정말 중요한 배열 형변환 = reshape 🔅
---


In [ ]:
a1 = np.arange(12) # 12개 인자를 만들어 보자
a1

In [ ]:
a1.shape # 몇차원? 형태

In [ ]:
a1.reshape(3, 4)

In [ ]:
a1.reshape(3, 4).shape

In [ ]:
a1 # a1은 그대로인 것! 중요!

In [ ]:
b2 = a1.reshape(3, 4)
b2

In [ ]:
b2.reshape(12)

In [ ]:
b2.shape

- 전체 원소 수 및 배열의 차원 계산하기 귀찮...

In [ ]:
a1

In [ ]:
a1.reshape(3, -1)

In [ ]:
a1.reshape(2, -1)

In [ ]:
a1.reshape(5, -1) #물론 만능은 아니다. 

In [ ]:
b2

In [ ]:
b2.reshape(-1) # b2 flatening = 1차원 벡터로 = flatten()

In [ ]:
b2.flatten() # 같은 것

In [ ]:
np.random.seed(7) # 같은 결과를 뽑기 위한 시드
np.random.randn(2,2)

In [ ]:
np.random.seed(7) # 같은 결과를 뽑기 위한 시드
np.random.randn(4).reshape(2,2) # 똑같은 결과

## e. why? 배열 --> 행렬 계산 feat. Vectorization 🤨
---
- 아래의 히든레이어 fully connected neural network를 back-propagation 가정<br><br>
<img src="https://raw.githubusercontent.com/tysep16/DV25_1/refs/heads/main/4x4matrix_FCN.png" width="600">
  
- 결국 아래의 연립방정식 풀이 --> x, y, z, w 계산

$\begin{cases}
y+z+w = 3 \\ 
x+z+w = 3 \\ 
x+y+w = 3 \\
x+y+z = 3 
\end{cases}$

- 행렬표현?
  
$\begin{bmatrix} 
0 & 1 & 1 & 1 \\
1 & 0 & 1 & 1 \\
1 & 1 & 0 & 1 \\
1 & 1 & 1 & 0 
\end{bmatrix}
\begin{bmatrix}
x \\ 
y \\ 
z \\ 
w 
\end{bmatrix} =
\begin{bmatrix}
3 \\ 
3 \\ 
3 \\ 
3 
\end{bmatrix}$

- 풀이

$\begin{bmatrix}
x \\ 
y \\ 
z \\ 
w 
\end{bmatrix} =
\begin{bmatrix} 
0 & 1 & 1 & 1 \\
1 & 0 & 1 & 1 \\
1 & 1 & 0 & 1 \\
1 & 1 & 1 & 0 
\end{bmatrix}^{-1}
\begin{bmatrix}
3 \\ 
3 \\ 
3 \\ 
3 
\end{bmatrix}$

In [ ]:
a = np.array([[0, 1, 1, 1], [1, 0, 1, 1], [1, 1, 0, 1], [1, 1, 1, 0]])
a

In [ ]:
b = np.array([3, 3, 3, 3]).reshape(4,1)
b

In [ ]:
b = np.array([3] * 4).reshape(4, 1)
b

In [ ]:
b = np.array([3, 3, 3, 3]) # 얘도 가능
b

- How? 역행렬 계산?

In [ ]:
_a = np.arange(4).reshape(2, 2)
_a

In [ ]:
np.linalg.inv(_a) # np.linalg.inv는 역행렬 구해주는 메소드

- 즉, $A*A^{-1}$ = $E$ 단위행렬

In [ ]:
_a @ np.linalg.inv(_a) # @ = 행렬곱

- 다시 FCN 문제로 돌아가서...

In [ ]:
np.linalg.inv(a) @ b

- input 노드 --> (x, y, z, w) = (1, 1, 1, 1)

## f. shape에 대한 유연성 = 좋아하진 않는다. 😥
---
- 엄밀하게는 아래의 행렬곱만이 가능하다. = (a, b) @ (c, d) = (a, d) --> b = c

In [ ]:
a = np.array([1, 2, 3, 4]).reshape(2, 2)
b = np.array([1, 2]).reshape(2, 1)
a@b

- a, b, a @ b 의 shape를 보면,

In [ ]:
a.shape, b.shape, (a@b).shape

- 다음과 같은 행렬 곱은 어떨까? --> 당연히 에러, why? b ~= c

In [ ]:
b = np.array([1, 2]).reshape(1, 2)
a@b

- but, 이건 가능 = b @ a

In [ ]:
b@a

In [ ]:
a.shape, b.shape, (b@a).shape

- 원래 항상 차원을 맞춰줘야 하지만, 아래와 같이 유연성 발휘

In [ ]:
b1 = np.array([1,2,3,4])
b2 = np.array([1,2,3,4]) 
b1@b2 

In [ ]:
b1.shape, b2.shape, (b1@b2).shape 

- (1,4) @ (4,1) = (1,1) 로 유연성 있게 처리. 원래는...

In [ ]:
b1 = np.array([1,2,3,4]).reshape(1,4) 
b2 = np.array([1,2,3,4]).reshape(4,1) 
b1@b2 

In [ ]:
b1.shape, b2.shape, (b1@b2).shape 

- 그래서 (4,1) @ (1,4)와 같은 계산은 직접 차원을 명시해야 함

In [ ]:
b1 = np.array([1,2,3,4]).reshape(4,1) 
b2 = np.array([1,2,3,4]).reshape(1,4) 
b1@b2 

#######

# 3. 차원과 축

## a. 넘파이 배열의 차원 --> .shape로 확인 가능 🧊
---
- 스칼라, 0d array

In [ ]:
a0 =np.array(3) 
a0, a0.shape

- 벡터, 1d array

In [ ]:
a1 = np.array(range(3*4)) 
a1, a1.shape

- 매트릭스, 2d array

In [ ]:
a2 = np.array(range(3*4)).reshape(3,4) 
a2, a2.shape

- 텐서, 3d array

In [ ]:
a3 = np.array(range(24)).reshape(2, 3, 4)
a3, a3.shape

## b. 넘파이 배열의 축(axis) ⚽
---
- 넘파이 벡터, 메트릭스, 텐서의 축(axis) <br>
<img src="https://raw.githubusercontent.com/tysep16/DV25_1/refs/heads/main/axis.png" width="600">

## c. concatenate 🗜️
---
- 벡터일 경우

In [2]:
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate([a, b])

array([1, 2, 3, 4])

- 매트릭스는?

In [ ]:
a = np.array([1, 2, 3, 4]).reshape(2, 2)
b = np.array(a + 4)
np.concatenate([a, b])

- 축 정의가 없으면 자동으로 위아래로 붙임 --> axis = 0

In [ ]:
np.concatenate([a, b], axis = 0)

In [ ]:
np.concatenate([a, b], axis = 1)

- 좀더 상황을 세분화 해보자.

In [ ]:
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6]).reshape(2,1)
c = np.array([10,11]).reshape(1,2)
a, b, c

In [ ]:
np.concatenate([a, c], axis = 0)

In [ ]:
np.concatenate([a, b], axis = 1)

In [ ]:
np.concatenate([a, b, c], axis = 0)

In [ ]:
np.concatenate([a, b.T, c],axis = 0)

In [ ]:
np.concatenate([a, b, c.T], axis = 1)

## c. 다른 방법? hstack, vstack 🛹
---
- 좀더 직관적...

In [ ]:
a = np.array([1, 2, 3, 4]).reshape(2, 2)
b = np.array(a + 4)
a, b

In [ ]:
np.vstack([a, b])

In [ ]:
np.concatenate([a, b], axis = 0)

In [ ]:
np.hstack([a, b])

In [ ]:
np.concatenate([a, b], axis = 1)

#######

# 4. 기타 계산함수들...

# a. 수학계산 7️⃣
---
- 제곱근, 지수, 로그, 삼각함수 가능

In [ ]:
a1 = np.array([1, 2, 3])

In [ ]:
l1 = [1, 2, 3]

In [ ]:
np.sqrt(a1), np.sqrt(l1) # 제곱근

In [ ]:
np.exp(a1), np.exp(l1) # 지수

In [ ]:
np.log(a1), np.log(l1) # 로그

In [ ]:
np.sin(a1), np.sin(l1)

## b. 축방향 사칙연산 🔢
---
- 행방향, 열방향 덧셈

In [ ]:
a = np.array([1,2,3,4,5,6]).reshape(3,2)
a

In [ ]:
a.sum()

In [ ]:
a.sum(axis = 0)

In [ ]:
a.sum(axis = 1)

## c. 축방향 통계연산 🥫
---
- mean, std, max, min, prod

In [ ]:
a = np.array([1,2,3,4,5,6,7,8]).reshape(4,2)
a

In [ ]:
a.mean(axis=0), a.std(axis=0), a.max(axis=0), a.min(axis=0), a.prod(axis=0)

In [ ]:
a.mean(axis=1), a.std(axis=1), a.max(axis=1), a.min(axis=1), a.prod(axis=1)

- 아! 물론,

In [ ]:
a.mean(), a.std(), a.max(), a.min(), a.prod()

# 5. 번외... why? 넘파이?

## a. 준비 = 시간구하기 👌
---

In [ ]:
import time

In [ ]:
t1 = time.time()

In [ ]:
t2 = time.time()

In [ ]:
t2 - t1 # 시간구하기

## b. 반복계산과 벡터계산 차이 🙌
---
- 5000*5000 랜덤 벡터 각 원소의 차이의 제곱을 구하는 코드 = 반복문 이용

In [ ]:
import time
import numpy as np

n = 5000
x = np.random.rand(n, n)
y = np.random.rand(n, n)

t1 = time.time()
for i in range(n):
    for j in range(n):
        z[i, j] = (x[i, j] - y[i, j])**2
t2 = time.time()
t2-t1      

- 5000*5000 랜덤 벡터 각 원소의 차이의 제곱을 구하는 코드 = 배열/행렬 이용

In [ ]:
t1 = time.time()
z = (x - y)**2
t2 = time.time()
t2 - t1

In [ ]:
(x - y)**2

In [ ]:
((x.reshape(n*n, 1) - y.reshape(n*n, 1))**2).reshape(n, n) # 방법2

In [ ]:
((x.reshape(-1) - y.reshape(-1))**2).reshape(n, n) # 방법3

# 6. 2주차 과제

## a. 다음 지시대로 빈 코드셀을 작성-->실행하여 캡처화면(jpg, png...)을 제출하세요. 😊
---
- 다음의 벡터를 넘파이 array()를 이용해서 출력하세요. *힌트: a0 = np.array([])*<br><br>
> $a0 = (1, 2, 3, 4)$

In [ ]:
a0 = np.array([1, 2, 3, 4])
a0

- 다음의 매트릭스를 넘파이 arange()를 이용해서 출력하세요.
- *힌트: a1 = np.arange().reshape()*<br><br>
> $ a1 = \begin{bmatrix} 
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7 \\
8 & 9 & 10 & 11 \\
12 & 13 & 14 & 15 
\end{bmatrix}$


In [ ]:
a1 = np.arange(16).reshape(4, 4)
a1

- 표준정규분포에서 16개의 표본을 추출하여 4*4 매트릭스를 출력하세요.
- *힌트: a2 = np.random.randn().reshape()*

In [ ]:
a2 = np.random.randn(4*4).reshape(4, 4)
a2

- 위에서 만든 매트릭스 a1에 a0를 열방향(axis=1) 방향으로 concatenate()를 이용해 병합해보세요.
- *힌트: 벡터 a0의 형태 주의 --> np.concatenate(❓, ❓.reshape(❓), axis=❓)*

In [ ]:
np.concatenate([a1, a0.reshape(4, 1)], axis=1)

- 위에서 만든 매트릭스 a1에 a2를 행방향(axis=0) 방향으로 vstack() or hstack()을 이용해 병합해보세요.
- *힌트: np.❓stack()*

In [ ]:
np.vstack([a1, a2])

- 위에서 만든 매트릭스 a2를 평균이 5이고 분산이 1인 표준정규분포에서 추출한 표본으로 구성된 매트릭스로 변환하세요.
- *힌트: 기존은 평균이 0, 분산이 1인 표준정규분포이므로... 만약 모든 매트릭스 인자에 5를 더하면 평균은? = 브로드캐스팅 이용*

In [ ]:
a2 + 5

- 위에서 만든 매트릭스 a1의 행방향 평균과 열방향 합을 각각 구하여 출력해 보세요.
- *힌트: np.mean(), np.sum()*

In [ ]:
np.mean(a1, axis=0), np.sum(a1, axis=1)

- 아래 행렬 식의 (x, y)를 계산하는 행렬곱 코드를 구현하세요. 
- *힌트: $AX = B$ --> $X = A^{-1}B$*

> $\begin{bmatrix} 
1 & 1 \\
1 & 0 \\
\end{bmatrix}
\begin{bmatrix}
x \\ 
y 
\end{bmatrix} =
\begin{bmatrix}
1 \\ 
2 
\end{bmatrix}$



In [ ]:
np.linalg.inv(np.array([[1, 1], [1, 0]])) @ np.array([1, 2]).reshape(2,1)